/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.gui;

import hotel.bo.HabitacionBO;
import hotel.entities.Empleado;
import hotel.entities.Habitacion;
import java.awt.GridLayout;
import java.awt.event.HierarchyBoundsListener;
import java.util.LinkedList;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Castro Mesen
 */
public class FrmPrincipal extends javax.swing.JFrame {
     
    private Habitacion matriz[][];
    private Habitacion h;
    private JFrame parent;
    private Empleado e;
    private int fila2;
    private int columna2;
    private HabitacionBO hbo;
    /**
     * Creates new form Principal
     */
    public FrmPrincipal(JFrame parent, Empleado e) {
        initComponents();
        setLocationRelativeTo(null);
        hbo = new HabitacionBO();
        this.parent = parent;
        this.e = e;
        fila2 = 2;
        columna2 = 2;
        matriz = new Habitacion[fila2][columna2];
        generar();
        asociarHab();
        char admin = 'a';
            if (e.getTipo() == admin) {
                FrmMantHabitacion dlg = new FrmMantHabitacion(this, matriz, fila2,columna2);
                dlg.pack();
                dlg.setVisible(true);
                
            }
            
            
            
    }
    
    
    public void asociarHab(){
        try {
            
            
                for (int f = 0; f < matriz.length; f++) {
                    for (int c = 0; c < matriz[f].length; c++) {
                        for (Habitacion h : hbo.buscar()) {
                        matriz[f][c] = h;
                    }
                }
            }
            
        }catch (RuntimeException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        catch (Exception e) {
        }
    }
            
            
            
    public void generar() {

        for (int f = 0; f < matriz.length; f++) {
            for (int c = 0; c < matriz[f].length; c++) {
                JButton btn;
                btn = new JButton();
                btn.setName(f + "," + c);
                GridLayout lal = new GridLayout(matriz.length, matriz[f].length);
                jPanel.setLayout(lal);
                jPanel.add(btn);
                btn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnactionPerformed(evt, btn);
                           //System.out.println(btn.getName());
                    }
                });

            }
        }

    }

    public void btnactionPerformed(java.awt.event.ActionEvent evt, JButton btn){
        
               String[] coordenada = btn.getName().split(",");
            int fila = Integer.parseInt(coordenada[0]);
            int columna = Integer.parseInt(coordenada[1]);
            System.out.println(fila + "-"+ columna);
            System.out.println(matriz[fila][columna]);
        
        
    }
    
    public boolean verHabitaciones(){
        for (int f = 0; f < matriz.length; f++) {
            for (int c = 0; c < matriz[f].length; c++) {
                if (matriz[f][c] == null) {
                    return true;
                }
            }
        }
        return false;
    }
    
    public void posicion(JButton btn){
        String[] coordenada = btn.getName().split(",");
            int fila = Integer.parseInt(coordenada[0]);
            int columna = Integer.parseInt(coordenada[1]);
        
    }
    
    
    
  
                                        

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
   
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
