/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.gui;

import hotel.bo.HabitacionBO;
import hotel.entities.Empleado;
import hotel.entities.Habitacion;
import java.awt.Color;
import java.awt.GridLayout;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author Castro Mesen
 */
public class FrmPrincipal extends javax.swing.JFrame {
     
    private Habitacion matriz[][];
    private Habitacion h;
    private JFrame parent;
    private Empleado e;
    private int fila2;
    private int columna2;
    private HabitacionBO hbo;
    /**
     * Creates new form Principal
     */
    public FrmPrincipal(JFrame parent, Empleado e) {
        initComponents();
        setLocationRelativeTo(null);
        hbo = new HabitacionBO();
        this.parent = parent;
        this.e = e;
        fila2 = 2;
        columna2 = 2;
        crearBotones();
        
          
    }
    
    
    private LocalDate verFecha(){
        LocalDate fecha = LocalDate.now();
        return fecha;
    }
    
                
            
    public void crearBotones(){
        jPanel.setLayout(new GridLayout(fila2, columna2));
        LinkedList<Habitacion> hab = hbo.buscar();
        for(Habitacion h : hab) {
            JButton btn = new JButton("#"+h.getId());
            btn.setName("btn,"+h.getId());
            if (h.getTipo().equals("Doble")) {
                btn.setBackground(Color.RED);
            }if (h.getTipo().equals("Matrimonial")) {
                btn.setBackground(Color.WHITE);
            }if (h.getTipo().equals("Sencilla")) {
                btn.setBackground(Color.BLUE);
            }if (h.getTipo().trim().equalsIgnoreCase("Suite Junior")) {
                btn.setBackground(Color.GREEN);
            }if (h.getTipo().trim().equalsIgnoreCase("Suite Doble")) {
                btn.setBackground(Color.ORANGE);
            }if (h.getTipo().equalsIgnoreCase("Suite Presidencial")) {
                System.out.println(h.getTipo().trim());
                btn.setBackground(Color.YELLOW);
            }
            
            btn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnactionPerformed(evt, btn);                         
                    }
                });
            jPanel.add(btn);
        }
    }

    public void btnactionPerformed(java.awt.event.ActionEvent evt, JButton btn){
        int id = Integer.parseInt(btn.getName().split(",")[1]);
        FrmReserva frm = new FrmReserva(this,id, e);
        frm.pack();
        frm.setVisible(true);
;    }
    
    public boolean verHabitaciones(){
        for (int f = 0; f < matriz.length; f++) {
            for (int c = 0; c < matriz[f].length; c++) {
                if (matriz[f][c] == null) {
                    return true;
                }
            }
        }
        return false;
    }
    
    public void posicion(JButton btn){
        String[] coordenada = btn.getName().split(",");
            int fila = Integer.parseInt(coordenada[0]);
            int columna = Integer.parseInt(coordenada[1]);
        
    }
    
    
    
  
                                        

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static void main(String[] args) {
        new FrmPrincipal(null, new Empleado()).setVisible(true);
    }
    
   
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    // End of variables declaration//GEN-END:variables
}
